[package]
name = "gtitem-r"
version = "0.1.0"
edition = "2021"
description = "Items.dat parser for Growtopia in Rust"
repository = "https://github.com/CLOEI/gtitem-r"
license = "MIT"
readme = "README.md"

[dependencies]
byteorder = "1.5.0"
